name: Push to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'main'

jobs:
  up:
    name: Package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v4
      with:
        images: ghcr.io/${{ github.repository }} # list of Docker images to use as base name for tags
        tag-sha: true # add git short SHA as Docker tag

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
